/**
 * Daily scripture for the stewardship layer.
 *
 * Verses are quoted from the World English Bible (WEB), which is in the
 * public domain — no license or attribution required, though the dashboard
 * card names the translation anyway.
 *
 * Each verse carries one theme so model() can match the day's verse to the
 * shape of the household's month (over plan → contentment, heavy debt →
 * debt, nothing set aside to give → giving, and so on). Selection is
 * deterministic by calendar day: both partners open the app and see the
 * same verse, and it changes at midnight, not on refresh.
 */

export const VERSE_THEMES = [
  "giving", "planning", "contentment", "debt", "provision", "diligence", "together",
];

export const VERSES = [
  // giving
  { ref: "Proverbs 3:9", theme: "giving",
    text: "Honor Yahweh with your substance, with the first fruits of all your increase." },
  { ref: "2 Corinthians 9:7", theme: "giving",
    text: "Let each man give according as he has determined in his heart, not grudgingly or under compulsion; for God loves a cheerful giver." },
  { ref: "Proverbs 11:25", theme: "giving",
    text: "The liberal soul shall be made fat. He who waters shall be watered also himself." },
  { ref: "Acts 20:35", theme: "giving",
    text: "Remember the words of the Lord Jesus, that he himself said, 'It is more blessed to give than to receive.'" },
  { ref: "Luke 6:38", theme: "giving",
    text: "Give, and it will be given to you: good measure, pressed down, shaken together, and running over, will be given to you." },
  { ref: "Proverbs 19:17", theme: "giving",
    text: "He who has pity on the poor lends to Yahweh; he will reward him." },
  { ref: "Proverbs 22:9", theme: "giving",
    text: "He who has a generous eye will be blessed, for he shares his food with the poor." },
  { ref: "2 Corinthians 9:6", theme: "giving",
    text: "He who sows sparingly will also reap sparingly. He who sows bountifully will also reap bountifully." },
  { ref: "Malachi 3:10", theme: "giving",
    text: "Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this, says Yahweh of Armies." },

  // planning
  { ref: "Proverbs 21:5", theme: "planning",
    text: "The plans of the diligent surely lead to profit; and everyone who is hasty surely rushes to poverty." },
  { ref: "Luke 14:28", theme: "planning",
    text: "For which of you, desiring to build a tower, doesn't first sit down and count the cost, to see if he has enough to complete it?" },
  { ref: "Proverbs 27:23", theme: "planning",
    text: "Know well the state of your flocks, and pay attention to your herds." },
  { ref: "Proverbs 24:3-4", theme: "planning",
    text: "Through wisdom a house is built; by understanding it is established; by knowledge the rooms are filled with all rare and beautiful treasure." },
  { ref: "Proverbs 6:6-8", theme: "planning",
    text: "Go to the ant, you sluggard. Consider her ways, and be wise; which having no chief, overseer, or ruler, provides her bread in the summer, and gathers her food in the harvest." },
  { ref: "Proverbs 16:3", theme: "planning",
    text: "Commit your deeds to Yahweh, and your plans shall succeed." },
  { ref: "Proverbs 15:22", theme: "planning",
    text: "Where there is no counsel, plans fail; but in a multitude of counselors they are established." },

  // contentment
  { ref: "1 Timothy 6:6", theme: "contentment",
    text: "But godliness with contentment is great gain." },
  { ref: "Hebrews 13:5", theme: "contentment",
    text: "Be free from the love of money, content with such things as you have, for he has said, 'I will in no way leave you, neither will I in any way forsake you.'" },
  { ref: "Philippians 4:12", theme: "contentment",
    text: "I know how to be humbled, and I also know how to abound. In everything and in all things I have learned the secret both to be filled and to be hungry, both to abound and to be in need." },
  { ref: "Proverbs 15:16", theme: "contentment",
    text: "Better is little, with the fear of Yahweh, than great treasure with trouble." },
  { ref: "Ecclesiastes 5:10", theme: "contentment",
    text: "He who loves silver shall not be satisfied with silver; nor he who loves abundance, with increase." },
  { ref: "Luke 12:15", theme: "contentment",
    text: "Beware! Keep yourselves from covetousness, for a man's life doesn't consist of the abundance of the things which he possesses." },
  { ref: "Matthew 6:21", theme: "contentment",
    text: "For where your treasure is, there your heart will be also." },
  { ref: "Proverbs 30:8", theme: "contentment",
    text: "Give me neither poverty nor riches. Feed me with the food that is needful for me." },

  // debt
  { ref: "Proverbs 22:7", theme: "debt",
    text: "The rich rule over the poor. The borrower is servant to the lender." },
  { ref: "Romans 13:8", theme: "debt",
    text: "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law." },
  { ref: "Psalm 37:21", theme: "debt",
    text: "The wicked borrow, and don't pay back, but the righteous give generously." },
  { ref: "Proverbs 22:26-27", theme: "debt",
    text: "Don't you be one of those who strike hands, of those who are collateral for debts. If you don't have means to pay, why should he take away your bed from under you?" },

  // provision
  { ref: "Matthew 6:26", theme: "provision",
    text: "See the birds of the sky, that they don't sow, neither do they reap, nor gather into barns. Your heavenly Father feeds them. Aren't you of much more value than they?" },
  { ref: "Philippians 4:19", theme: "provision",
    text: "My God will supply every need of yours according to his riches in glory in Christ Jesus." },
  { ref: "Matthew 6:33", theme: "provision",
    text: "But seek first God's Kingdom and his righteousness; and all these things will be given to you as well." },
  { ref: "Psalm 23:1", theme: "provision",
    text: "Yahweh is my shepherd; I shall lack nothing." },
  { ref: "Matthew 6:34", theme: "provision",
    text: "Therefore don't be anxious for tomorrow, for tomorrow will be anxious for itself. Each day's own evil is sufficient." },
  { ref: "Proverbs 10:22", theme: "provision",
    text: "Yahweh's blessing brings wealth, and he adds no trouble to it." },

  // diligence — earning, keeping, and building slowly
  { ref: "Proverbs 21:20", theme: "diligence",
    text: "There is precious treasure and oil in the dwelling of the wise, but a foolish man swallows it up." },
  { ref: "Proverbs 13:11", theme: "diligence",
    text: "Wealth gained dishonestly dwindles away, but he who gathers by hand makes it grow." },
  { ref: "Proverbs 10:4", theme: "diligence",
    text: "He becomes poor who works with a lazy hand, but the hand of the diligent brings wealth." },
  { ref: "Proverbs 13:22", theme: "diligence",
    text: "A good man leaves an inheritance to his children's children." },
  { ref: "Proverbs 28:20", theme: "diligence",
    text: "A faithful man is rich with blessings; but one who is eager to be rich will not go unpunished." },

  // together — two people, one plan
  { ref: "Ecclesiastes 4:9", theme: "together",
    text: "Two are better than one, because they have a good reward for their labor." },
  { ref: "Ecclesiastes 4:12", theme: "together",
    text: "If a man prevails against one who is alone, two shall withstand him; and a threefold cord is not quickly broken." },
  { ref: "Amos 3:3", theme: "together",
    text: "Do two walk together, unless they have agreed?" },
];

// Stable index for "today" — same all day, ticks over at local midnight.
export const dayIndex = (d = new Date()) =>
  d.getFullYear() * 372 + d.getMonth() * 31 + (d.getDate() - 1);

/**
 * Today's verse. Pass a theme to draw from that theme's pool (model() picks
 * one from the month's shape); pass null to rotate through everything.
 */
export function verseForDay(theme, d = new Date()) {
  const pool = theme ? VERSES.filter((v) => v.theme === theme) : VERSES;
  const list = pool.length ? pool : VERSES;
  return list[dayIndex(d) % list.length];
}

/**
 * A short daily Bible study on money and wisdom. Each has a passage (WEB),
 * a two-line reflection tying it to a household's finances, a question the
 * couple can talk through, and a one-line prayer. Deterministic by day so
 * both partners open the same study; rotates on roughly a monthly cycle.
 */
export const STUDIES = [
  { day: "Every dollar has a job", ref: "Proverbs 21:5",
    text: "The plans of the diligent surely lead to profit; and everyone who is hasty surely rushes to poverty.",
    reflect: "Wealth rarely comes from a windfall; it comes from small, deliberate plans kept over time. A budget is not a cage — it's diligence written down.",
    ask: "What is one hasty money habit we could turn into a planned one this month?",
    pray: "Father, make us diligent and unhurried with what You've given us." },
  { day: "Count the cost first", ref: "Luke 14:28",
    text: "For which of you, desiring to build a tower, doesn't first sit down and count the cost, to see if he has enough to complete it?",
    reflect: "Jesus assumes His followers plan ahead. Counting the cost before you commit is not a lack of faith — it's the wisdom faith produces.",
    ask: "Is there a purchase or plan we've started without fully counting the cost?",
    pray: "Lord, give us the patience to count the cost before we begin." },
  { day: "The borrower and the lender", ref: "Proverbs 22:7",
    text: "The rich rule over the poor. The borrower is servant to the lender.",
    reflect: "Debt is not a sin, but it is a form of servitude — it hands part of your future to someone else. Every payment made is a little freedom bought back.",
    ask: "What would being free of one debt let us say yes to?",
    pray: "God, give us discipline to loosen debt's hold and walk in freedom." },
  { day: "First fruits, not leftovers", ref: "Proverbs 3:9",
    text: "Honor Yahweh with your substance, with the first fruits of all your increase.",
    reflect: "Giving first — before the bills, before the wants — is how we keep money a tool and not a master. What we give away, we can never lose to worry.",
    ask: "Does our giving come off the top, or out of what's left over?",
    pray: "Lord, let generosity be our first move, not our last." },
  { day: "Content in every state", ref: "Philippians 4:12",
    text: "I know how to be humbled, and I also know how to abound. In everything and in all things I have learned the secret both to be filled and to be hungry.",
    reflect: "Contentment is a skill Paul says he learned — it isn't automatic. It grows in the plenty and in the pinch alike, and it quiets the endless 'more.'",
    ask: "Where has 'a little more' been stealing our peace lately?",
    pray: "Teach us, Lord, the secret of being content in what we have." },
  { day: "Treasure and the heart", ref: "Matthew 6:21",
    text: "For where your treasure is, there your heart will be also.",
    reflect: "Your calendar and your bank statement tell the truth about what you love. Move the money, and over time the heart tends to follow.",
    ask: "If a stranger read our spending, what would they say we treasure?",
    pray: "Father, put our treasure where we most want our hearts to be." },
  { day: "Two are better than one", ref: "Ecclesiastes 4:9",
    text: "Two are better than one, because they have a good reward for their labor.",
    reflect: "Money is one of the places a marriage is most tested — and most strengthened. Handling it together, honestly, turns a stress into a shared victory.",
    ask: "What money conversation have we been avoiding that we could have this week?",
    pray: "Lord, make us truly one in how we steward our home." },
  { day: "The ant's quiet wisdom", ref: "Proverbs 6:6-8",
    text: "Go to the ant, you sluggard. Consider her ways, and be wise; which having no chief, provides her bread in the summer, and gathers her food in the harvest.",
    reflect: "The ant saves in the season of plenty for the season of need — no one making her do it. Saving is simply preparing today for a tomorrow you can't yet see.",
    ask: "Are we storing anything up for the lean season, or spending every harvest?",
    pray: "God, give us the ant's quiet foresight." },
  { day: "Rich toward God", ref: "Luke 12:15",
    text: "Beware! Keep yourselves from covetousness, for a man's life doesn't consist of the abundance of the things which he possesses.",
    reflect: "A fuller garage never made a fuller life. Jesus warns that the size of the pile and the size of the life are two different measures.",
    ask: "What are we tempted to believe one more purchase will finally give us?",
    pray: "Lord, keep us from mistaking abundance for life." },
  { day: "Owe no one anything", ref: "Romans 13:8",
    text: "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law.",
    reflect: "Paul sets one debt we should always carry — love — and points us to settle the rest. Paying what we owe is part of loving well.",
    ask: "Is there a debt, big or small, we could make a plan to clear?",
    pray: "Father, free us to owe only love." },
  { day: "Enough for today", ref: "Proverbs 30:8",
    text: "Give me neither poverty nor riches. Feed me with the food that is needful for me.",
    reflect: "This is a rare prayer: not for wealth, but for enough. Enough keeps us from the desperation of too little and the forgetfulness of too much.",
    ask: "What does 'enough' actually look like for our household?",
    pray: "Give us this day, Lord, our daily bread — no more, no less." },
  { day: "Wealth gathered little by little", ref: "Proverbs 13:11",
    text: "Wealth gained dishonestly dwindles away, but he who gathers by hand makes it grow.",
    reflect: "Slow money lasts. What is built handful by handful puts down roots that quick money never does.",
    ask: "What's one small, steady habit we could gather 'by hand' this year?",
    pray: "Lord, teach us to build slowly and honestly." },
  { day: "The cheerful giver", ref: "2 Corinthians 9:7",
    text: "Let each man give as he has determined in his heart, not grudgingly or under compulsion; for God loves a cheerful giver.",
    reflect: "Giving decided ahead of time, in the heart, is giving that lasts. It's not the amount God delights in first — it's the gladness.",
    ask: "Is our giving planned and glad, or reactive and reluctant?",
    pray: "Make us cheerful givers, Lord, not grudging ones." },
  { day: "A good name over riches", ref: "Proverbs 22:1",
    text: "A good name is more desirable than great riches, and loving favor is better than silver and gold.",
    reflect: "How you handle money builds — or spends — your reputation. Paying on time, keeping your word, dealing fairly: these are worth more than the balance.",
    ask: "Does the way we handle money match the name we want to be known by?",
    pray: "Father, let our integrity outshine our income." },
  { day: "Do not wear yourself out for wealth", ref: "Proverbs 23:4",
    text: "Don't weary yourself to be rich. In your wisdom, show restraint.",
    reflect: "There is a striving that costs more than it earns — health, marriage, presence. Wisdom knows when to stop chasing.",
    ask: "Where might we be wearing ourselves out for money at the expense of what matters more?",
    pray: "Lord, give us restraint and rest." },
  { day: "The generous are enriched", ref: "Proverbs 11:25",
    text: "The liberal soul shall be made fat. He who waters shall be watered also himself.",
    reflect: "Generosity has a strange arithmetic: giving it away enlarges the giver. Open hands, it turns out, are the ones best able to receive.",
    ask: "Who could we water this month — with money, or with more than money?",
    pray: "God, make our hands open and our souls generous." },
  { day: "Faithful in little", ref: "Luke 16:10",
    text: "He who is faithful in a very little is faithful also in much; and he who is unrighteous in a very little is also unrighteous in much.",
    reflect: "God watches how we handle small amounts, because character is the same at every scale. The habits of the small paycheck are the habits of the large one.",
    ask: "Are we faithful with the small things — the $20 decisions — not just the big ones?",
    pray: "Lord, make us trustworthy in little and in much." },
  { day: "Where moth and rust destroy", ref: "Matthew 6:19-20",
    text: "Don't lay up treasures for yourselves on the earth, where moth and rust consume, but lay up treasures in heaven.",
    reflect: "Earthly wealth is always leaking — it rusts, breaks, and fades. Jesus points us to an account that never depreciates.",
    ask: "What's one way we could invest in something eternal this week?",
    pray: "Father, help us store up what moth and rust can't touch." },
  { day: "The plans of the heart", ref: "Proverbs 16:3",
    text: "Commit your deeds to Yahweh, and your plans shall succeed.",
    reflect: "We plan, but we hold the plans loosely and offer them up. Committed to God, even our budgets become a form of trust.",
    ask: "Have we invited God into our financial plans, or only our prayers?",
    pray: "We commit our plans to You, Lord — establish them." },
  { day: "He gives power to get wealth", ref: "Deuteronomy 8:18",
    text: "You shall remember Yahweh your God, for it is he who gives you power to get wealth.",
    reflect: "Every ability to earn — your health, your skill, your opportunity — is a gift. Remembering the Giver keeps success from becoming pride.",
    ask: "Do we thank God for the ability to earn, not just the earnings?",
    pray: "We remember, Lord, that all we have came first from You." },
  { day: "Better a little with peace", ref: "Proverbs 15:16",
    text: "Better is little, with the fear of Yahweh, than great treasure with trouble.",
    reflect: "A small budget held in peace beats a large one held in anxiety. Peace, not the number, is the real measure of wealth.",
    ask: "Would we trade some income for more peace? Have we already, without noticing?",
    pray: "Lord, we'd rather have little with You than much without You." },
  { day: "The sluggard and the diligent", ref: "Proverbs 10:4",
    text: "He becomes poor who works with a lazy hand, but the hand of the diligent brings wealth.",
    reflect: "Diligence isn't frantic — it's consistent. The steady hand, applied over months, quietly outpaces the burst of effort that fades.",
    ask: "What's one financial task we keep putting off that diligence would just do?",
    pray: "God, steady our hands for the work in front of us." },
  { day: "Give and it will be given", ref: "Luke 6:38",
    text: "Give, and it will be given to you: good measure, pressed down, shaken together, and running over.",
    reflect: "God's economy runs on overflow, not scarcity. What we release in trust, He has a way of returning in fuller measure.",
    ask: "Where is fear of scarcity keeping our hands closed?",
    pray: "Teach us to give freely and trust You for the measure." },
  { day: "An inheritance for the children", ref: "Proverbs 13:22",
    text: "A good man leaves an inheritance to his children's children.",
    reflect: "Stewardship thinks past this month, even past this life. What we build wisely can bless people we may never meet.",
    ask: "What are we building now that could bless the next generation?",
    pray: "Father, help us leave more than we spend." },
  { day: "Godliness with contentment", ref: "1 Timothy 6:6",
    text: "But godliness with contentment is great gain.",
    reflect: "The world measures gain by accumulation; Paul measures it by contentment. The richest household is the one that has learned to be satisfied.",
    ask: "What would 'great gain' look like if we measured it Paul's way?",
    pray: "Lord, make godliness and contentment our real wealth." },
  { day: "Know your flocks", ref: "Proverbs 27:23",
    text: "Know well the state of your flocks, and pay attention to your herds.",
    reflect: "You can't steward what you won't look at. Simply knowing where your money is — honestly, regularly — is half of wisdom.",
    ask: "Do we actually know the state of our 'flocks' this month?",
    pray: "Lord, give us the courage to look clearly at what we have." },
  { day: "The love of money", ref: "1 Timothy 6:10",
    text: "For the love of money is a root of all kinds of evil.",
    reflect: "Money itself is neutral — a tool. It's the love of it, the grip it gets on the heart, that does the damage. Hold it loosely.",
    ask: "Is money a tool in our hands, or has it become something we serve?",
    pray: "Guard our hearts, Lord, from loving what we're meant to use." },
  { day: "Cast your bread on the waters", ref: "Ecclesiastes 11:1-2",
    text: "Cast your bread on the waters; for you shall find it after many days. Give a portion to seven, yes, even to eight.",
    reflect: "Wisdom diversifies and gives widely, trusting a return it can't yet see. Generosity and prudence are not opposites here — they're partners.",
    ask: "Are we spreading our giving and our saving wisely, or all in one basket?",
    pray: "Lord, help us give and invest with open, trusting hands." },
  { day: "No one can serve two masters", ref: "Matthew 6:24",
    text: "No one can serve two masters... You can't serve both God and Mammon.",
    reflect: "Money makes a fine servant and a cruel master. Jesus says there's no shared throne — one of them will rule the house.",
    ask: "In honest moments, which one is running our decisions?",
    pray: "Father, be the only Master of our home and our money." },
  { day: "The blessing that adds no sorrow", ref: "Proverbs 10:22",
    text: "Yahweh's blessing brings wealth, and he adds no trouble to it.",
    reflect: "There's a kind of provision that comes without the strings of stress, guilt, or striving. That's the increase worth praying for.",
    ask: "Are we chasing gain that brings trouble, or open to the blessing that doesn't?",
    pray: "Lord, we ask for the blessing that carries no sorrow." },
  { day: "Seek first the Kingdom", ref: "Matthew 6:33",
    text: "But seek first God's Kingdom and his righteousness; and all these things will be given to you as well.",
    reflect: "Jesus doesn't ignore our needs — He reorders them. Put the Kingdom first, and the daily needs fall into their proper place behind it.",
    ask: "What would it look like to seek the Kingdom first in our budget this month?",
    pray: "Lord, be first — and we'll trust You with the rest." },
];

export function studyForDay(d = new Date()) {
  return STUDIES[dayIndex(d) % STUDIES.length];
}
